Repository appuio/openshift4-docs, pull requests merged in 2021-11, with the labels that each got.

#134 Respect exoscale zones in cluster setup instructions
  docs/modules/ROOT/pages/how-tos/exoscale/install.adoc
  docs/modules/ROOT/partials/exoscale/environment-vars.adoc
Labels: bug

#133 Update OCP version in install guide to 4.9
  docs/modules/ROOT/pages/how-tos/cloudscale/install.adoc
  docs/modules/ROOT/pages/how-tos/exoscale/install.adoc
  docs/modules/ROOT/partials/install/prepare-terraform.adoc
Labels: enhancement

#139 Fix Terraform command for creating hieradata in clouscale.ch install guide
  docs/modules/ROOT/pages/how-tos/cloudscale/install.adoc
Labels: bug

#138 Replace storage node on cloudscale.ch
  docs/modules/ROOT/pages/how-tos/cloudscale/install.adoc
  docs/modules/ROOT/pages/how-tos/cloudscale/replace-storage-node.adoc
  docs/modules/ROOT/pages/how-tos/exoscale/add_storage_node.adoc
  docs/modules/ROOT/pages/how-tos/exoscale/change_storage_node_size.adoc
  docs/modules/ROOT/pages/how-tos/exoscale/remove_storage_node.adoc
  docs/modules/ROOT/pages/how-tos/exoscale/replace_storage_node.adoc
  docs/modules/ROOT/partials/cloudscale/configure-terraform-secrets.adoc
  docs/modules/ROOT/partials/cloudscale/environment-vars.adoc
  docs/modules/ROOT/partials/cloudscale/prerequisites.adoc
  docs/modules/ROOT/partials/cloudscale/setup-local-env.adoc
  docs/modules/ROOT/partials/create-replacement-storage-node.adoc
  docs/modules/ROOT/partials/delete-storage-node.adoc
  docs/modules/ROOT/partials/install/bootstrap-nodes.adoc
  docs/modules/ROOT/partials/label-taint-storage-nodes.adoc
  docs/modules/ROOT/partials/nav-howtos.adoc
  docs/modules/ROOT/partials/storage-ceph-remove-mon.adoc
Labels: documentation

#137 Add how-to on enabling LoadBalancer services on cloudscale.ch
  docs/modules/ROOT/pages/how-tos/cloudscale/enable-loadbalancer-service.adoc
  docs/modules/ROOT/partials/nav-howtos.adoc
Labels: documentation, enhancement
